### ISSUE TITLE
Navigation padding

### ISSUE THREAD

**Issue by eko24ive** [Finkler1989/Home-work-5#1]
Here is how your navigation looks:
![image](https://cloud.githubusercontent.com/assets/25591824/23283971/9231bd10-fa31-11e6-965e-6e206b03e02f.png)

Please add some margin, so it'll look like on the design:
![image](https://cloud.githubusercontent.com/assets/25591824/23283990/a25eca16-fa31-11e6-93c8-20f17ed776cf.png)

**Comment by Finkler1989** [comment]
Fixed

**Comment by eko24ive** [comment]
Yep, I see - now it's looks really good, nice job !
