### ISSUE TITLE
Horizontal line width

### ISSUE THREAD

**Issue by eko24ive** [Finkler1989/Home-work-5#2]
Your line is full width:
![image](https://cloud.githubusercontent.com/assets/25591824/23284009/c2b10414-fa31-11e6-824e-bb125566bc23.png)

While it's scaled to wrapper on the design:
![image](https://cloud.githubusercontent.com/assets/25591824/23284024/ddcd0f36-fa31-11e6-89d4-f6d92f4efb04.png)

**Comment by Finkler1989** [comment]
Fixed

**Comment by eko24ive** [comment]
Great joob, keep it up !
