### ISSUE TITLE
Footer mismatch

### ISSUE THREAD

**Issue by eko24ive** [Finkler1989/Home-work-5#3]
Here is your footer:
![image](https://cloud.githubusercontent.com/assets/25591824/23284033/ea7dcafe-fa31-11e6-8526-b715f960430c.png)

Compare it to design, and add missing styles:
![image](https://cloud.githubusercontent.com/assets/25591824/23284046/fe60db6a-fa31-11e6-9cb6-539810eefa77.png)

**Comment by Finkler1989** [comment]
Fixed

**Comment by eko24ive** [comment]
Good job !
